# Generated by Django 5.1.6 on 2025-02-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_song_playlist'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playlist',
            table='Playlist',
        ),
        migrations.AlterModelTable(
            name='song',
            table='Song',
        ),
    ]
