# Generated by Django 5.1.6 on 2025-02-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_playlist_table_alter_song_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='updateprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('genres', models.TextField(help_text='Comma-separated genres')),
                ('artists', models.TextField(help_text='Comma-separated artist names')),
            ],
            options={
                'db_table': 'updateprofile',
            },
        ),
    ]
