# Generated by Django 5.1.6 on 2025-02-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_updateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='username',
            field=models.CharField(default='default_username', max_length=255),
        ),
    ]
