# Generated by Django 5.1.6 on 2025-02-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_user1_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='username',
            new_name='user',
        ),
    ]
