# Generated by Django 5.1.6 on 2025-02-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_username_user1_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
