# Generated by Django 5.1.6 on 2025-02-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_playlist_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='picfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purl', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'picfile',
            },
        ),
    ]
