# Generated by Django 5.1.6 on 2025-02-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_picfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picfile',
            name='purl',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
